function plothist(hstgrm);
% Plot a histogram generated by makedenshist.
% Actually, as long as
% hstgrm(1,:) = the list of bin centers, and
% hstgrm(2,:) = normalized histogram heights,
% plothist will work for you.
bar(hstgrm(1,:),hstgrm(2,:),'hist')
h = findobj(gca,'Type','patch');
set(h,'FaceColor','w','EdgeColor','k')